on:
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: read

jobs:
  release-on-push:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - id: release
        uses: rymndhng/release-on-push-action@master
        with:
          bump_version_scheme: minor
      
      - uses: actions/checkout@v2
        with:
          ref: ${{ steps.release.outputs.tag_name }}

      - name: deploy
        env:
          TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
          VERSION_NUMBER: ${{ steps.release.outputs.tag_name }}
        run: |

          echo "Deploying ${{ steps.release.outputs.tag_name }} to PyPI"
          pip install twine
          python setup.py sdist
          twine upload dist/* -u $TWINE_USERNAME -p $TWINE_PASSWORD